config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  match 'tweets' => 'tweets#index', via: [:get, :post]
  get '/:handle', to: 'tweets#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # password=(unencrypted virtual attribute)
  # validates presence of password, password_confirmation
  # authenticate(unentrypted password)
  #
  # Much of the secure password machinery will be
  # implemented using a single Rails method called
  # has_secure_password. Because so much depends on
  # this one method, it is difficult to develop
  # secure passwords incrementally
  #
  # 1. need bcrypt, and password_digest on model
  # 2. password & password_confirmation are virtual
  #    attrs that must match. all taken care of by 
  #    has_secure_password
  # 3. presence validations auto added too
  # 4. as long as there is a password_digest column
  #    in the database, adding this one method to our
  #    model gives us a secure way to create and
  #    authenticate new users
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase } 
  validates :name,     length: { maximum: 50 }, 
                       presence: true
  validates :email,    length: { maximum: 250 }, 
                       format: { with: VALID_EMAIL_REGEX },
                       uniqueness: { case_sensitive: false },
                       presence: true
  validates :password, length: { minimum: 6 },
                       presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private def logged_in_user
    unless logged_in?
      flash[:danger] = "UNAUTHORIZED! You must login."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
    
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :logged_in_user
  before_action :user_timeline

  def index
  end

  def show
  end

  private 

  def sanitize_handle
    params[:handle].gsub("@", "")
  end

  def user_timeline
    @tweets = $client.user_timeline(sanitize_handle, count: 25) if params[:handle]
  rescue Twitter::Error::NotFound => e
    flash.now[:danger] = "#{params[:handle]} is not a valid Twitter handle"
  rescue Twitter::Error::Unauthorized => e
    flash.now[:danger] = "Sorry, searching for #{params[:handle]} is unauthorized"
  ensure
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # http://guides.rubyonrails.org/action_controller_overview.html#session
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetstack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Droid+Sans+Mono' rel='stylesheet' type='text/css'>
  </head>

  <body class="index">
    <header class="heading">
      <% if logged_in? %>
        <%= "Chirp, #{@current_user.name}!" %><br>
        <%= link_to(logout_path, method: "delete") do %>
          &raquo; log out
        <% end %>
      <% end %>

      <h1 class="title">TweetStack</h1>
      <pre>
          .-"-.
         / 4 4 \
         \_ v _/
         //   \\
        ((     ))
  =======""===""=======
           |||
           '|'
      </pre>
      <p>Enter a Twitter handle to get recent tweets:</p>
    </header>

    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<%= form_tag tweets_path, method: 'post', class: "pull-left" do %>
  <div class="field">
    <%= text_field_tag :handle, params[:handle], class: "form-control", placeholder: "@dhh" %>
  </div>
  <div class="actions">
    <%= submit_tag "Get Tweets", class: "btn btn-submit" %>
  </div>
<% end %>

<section id="tweets">
  <% unless @tweets.blank? %>
    <h2><%= @tweets.first.user.screen_name %>'s Recent Tweets:</h2> 
    <ol>
      <% @tweets.each do |tweet| %>
        <li>
          <%= link_to tweet.full_text, "https://www.twitter.com/#{tweet.user.screen_name}" %><br>
          <small><%= tweet.created_at.try(:strftime, '%m/%d/%Y %I:%M%P') %></small>
          <% tweet.user_mentions.each do |mention| %>
            <br><%= link_to "See tweets for #{mention.name} >>", "/#{mention.name}", class: "mentions" %>
            <br><%= link_to "Or visit them on Twitter >>", "https://www.twitter.com/#{mention.screen_name}", class: "mentions" %>
          <% end %>
        </li>
      <% end %>
    </ol>
  <% end %>
  <%= link_to("or just go to Twitter instead >>", "https://twitter.com") %>
</section>